### ISSUE TITLE
Date picker breaks on Chromium browsers

### ISSUE THREAD

**Issue by 4very** [rcos/observatory-new#26]
**Describe the bug**
The expected date format from the system does not coincide with the forced date format in Chromium browsers.

**To Reproduce**
Steps to reproduce the behavior (On Chromium browser):
1. Go to calendar
2. Click "New Event"
3. Try to fill out an event

**Expected behavior**
The forced date format should be consistent across all browser types. 

**Screenshots**
https://i.imgur.com/EDmQrUs.png

**Comment by 4very** [comment]
This bug is also appears whenever you try to add a story, since you need a date.

**Comment by rushsteve1** [comment]
Marking this as "Good first issue" since the solution should be fairly simple.

You should just have to add a case for the Chromium style dates to [this function](https://github.com/rcos/observatory-new/blob/a341f14e63cbd4d94ede1fdfb8d20b01d4345aeb/src/calendar/models.rs#L84) and its [other related one](https://github.com/rcos/observatory-new/blob/a341f14e63cbd4d94ede1fdfb8d20b01d4345aeb/src/news/models.rs#L25).

**Comment by rushsteve1** [comment]
The Chrono [`strftime`](https://docs.rs/chrono/0.4.6/chrono/format/strftime/index.html) module is also important to handling the dates in the backend.

Also as @sommea pointed out using the [Bootstrap date picker](https://eonasdan.github.io/bootstrap-datetimepicker/) would be useful and more cross-browser than the existing solution.

**Comment by rushsteve1** [comment]
Due to having to deal with `strftime` and Chrono as well as maybe doing the Boostrap date picker I have remove the Good First Issue tag from this.

**Comment by rushsteve1** [comment]
Closed with #60
