### ISSUE TITLE
Last links extend to entire table

### ISSUE THREAD

**Issue by OliviaLundelius** [rcos/observatory-new#38]
**Describe the bug**
<a> tag extends to encompass entire table sometimes on users, projects, groups, etc.  Happens often in Edge, but also occurs in other chrome-based browsers.

**Comment by rushsteve1** [comment]
So this is an issue related to the [Bootstrap stretched link](https://getbootstrap.com/docs/4.3/utilities/stretched-link/) where it is stretching to a larger area than intended.

I believe this can be fixed by changing every `<td>` element like this one
https://github.com/rcos/observatory-new/blob/a341f14e63cbd4d94ede1fdfb8d20b01d4345aeb/templates/user/users-list.html#L30
to one of these:
- `<td class="container">`
- `<td><div class="container">`

However I have not tested this so I am not sure if that is going to work or not.

**Comment by rushsteve1** [comment]
Required a JavaScript workaround to fix it.
